### ISSUE TITLE
SDCollisionVis doesn't compile on 5.6

### ISSUE THREAD

**Issue by TheEnbyWitch** [splash-damage/collisionvis#1]
Hey there!
I tried compiling the plugin in UE5.6 and it gave me a compile error.
```
Determining max actions to execute in parallel (12 physical cores, 24 logical cores)
  Executing up to 24 processes, one per logical core
  Requested 1.5 GB memory per action, 27.12 GB available: limiting max parallel actions to 18
Using Unreal Build Accelerator executor to run 10 action(s)
  Storage capacity 40Gb
---- Starting trace: 251203_160601 ----
UbaSessionServer - Disable remote execution (remote sessions will finish current processes)
------ Building 10 action(s) started ------
** For PlatformerGameEditor-Win64-Development **
[1/10] Compile [x64] Module.SDCollisionVis.cpp
[2/10] Compile [x64] Module.GGAbilitiesTest.cpp
[3/10] Link [x64] UnrealEditor-GGAbilitiesTest.lib
[4/10] Compile [x64] SDCollisionVisModule.cpp
11>MeshDrawCommands.h(10,1): Error C1083 : Cannot open include file: 'TranslucentPassResource.h': No such file or directory
#include "TranslucentPassResource.h"
^
[5/10] Compile [x64] SDCollisionVisRenderer.cpp
11>MeshDrawCommands.h(10,1): Error C1083 : Cannot open include file: 'TranslucentPassResource.h': No such file or directory
#include "TranslucentPassResource.h"
^
[6/10] Link [x64] UnrealEditor-GGAbilitiesTest.dll
[7/10] Compile [x64] SDCollisionVisSettings.cpp
11>MeshDrawCommands.h(10,1): Error C1083 : Cannot open include file: 'TranslucentPassResource.h': No such file or directory
#include "TranslucentPassResource.h"
^
Trace written to file C:/Dev/Platformer/Engine/Programs/UnrealBuildTool/Log.uba with size 5.4kb
Total time in Unreal Build Accelerator local executor: 8.22 seconds

Result: Failed (OtherCompilationError)
Total execution time: 37.15 seconds
11>Microsoft.MakeFile.Targets(44,5): Error MSB3073 : The command "..\..\Build\BatchFiles\Build.bat -Target="PlatformerGameEditor Win64 Development -Project=\"C:\Dev\Platformer\PlatformerGame\PlatformerGame.uproject\"" -Target="ShaderCompileWorker Win64 Development -Project=\"C:\Dev\Platformer\PlatformerGame\PlatformerGame.uproject\" -Quiet" -WaitMutex -FromMsBuild -architecture=x64" exited with code 6.
```
Haven't checked 5.7 as I'm not planning on upgrading just yet.

**Comment by alister-chowdhury** [comment]
Hey, thanks for the report!

This was originally first launched with fixes for 5.7, so I wouldn't have been massively surprised if this had some issues compiling with 5.6.
If there is a demand for 5.6 support, it shouldn't be too hard to accommodate that.

How did you include this in your project?
I'm realising now that at no point in the documentation did we mention we expected you to git clone this into `Engine/Plugins` (`$Project/Plugins` may work too, although internally, we haven't tested that yet).

The actual error itself is quite interesting, as we don't directly include, `MeshDrawCommands.h`, which cannot find `TranslucentPassResource.h`.
(Pretty sure it's coming from `SceneRendering.h`, which is included in `ScenePrivate.h`, which we include).
Given that, I don't think this should have anything to do with what Engine version you're on.

I'll do a clean clone of 5.6, include the plugin and see if there's something I overlooked!

**Comment by alister-chowdhury** [comment]
So I did:

```
git clone --depth 1 --branch 5.6.0-release git@github.com:EpicGames/UnrealEngine.git
cd UnrealEngine\Engine\Plugins
git clone git@github.com:splash-damage/collisionvis.git SDCollisionVis
cd ..\..
Setup.bat
GenerateProjectFiles.bat
```

And everyone  worked as expected, I am going to submit a change soon that adds better documentation for installing and adds support UE5.6

**Comment by alister-chowdhury** [comment]
Please let me know how you get on with that

**Comment by TheEnbyWitch** [comment]
I cloned this into the project folder at first, I'll try the engine one.

**Comment by TheEnbyWitch** [comment]
<img width="994" height="1010" alt="Image" src="https://github.com/user-attachments/assets/c52aaa91-3e32-499b-a43c-804ccb63c7b3" />
worked perfectly, thank you!!
